description: "TDS Virtual TA Project Sample (but not the actual evaluation) Questions"

providers:
  - id: https
    config:
      url: https://virtualta.onrender.com/ # Replace this with your API endpoint
      method: POST
      headers:
        Content-Type: application/json
      body: |
        {
          "question": "{{ question }}"{% if image %},
          "image": "{{ image }}"{% endif %}
        }
      transformResponse: json

# Ensure JSON schema
defaultTest:
  options:
    provider: google:gemini-2.0-flash
  assert:
    - type: is-json
      value:
        type: object
        required: [answer, links]
        properties:
          answer: { type: string }
          links:
            type: array
            items:
              type: object
              required: [url, text]
              properties:
                url: { type: string }
                text: { type: string }

tests:
  
  
  - vars:
      question: When is the project 1 deadline?
    assert:
      - type: llm-rubric
        transform: output.answer
        value: 16th February 2025
      - type: llm-rubric
        transform: output.links
        value: discourse
  

writeLatestResults: true

commandLineOptions:
  cache: true